# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cbc18667bbda784a2ee8a3aa8aacedf0fa6950e6ba90893b00e1af2e3d614d1b533a6035ecf69bf19c6eacc591b37742bf81b1f50bba249f6d3c4f760eaf51a

test:
  secret_key_base: ba11e33da47826a6c6869c319d387cdb3c09d870631084dbdeaa4306d12e694ca89de83a7befe37a98223b6eae57c21ae2bcd92c18d98cabfb2f937edd3d1cdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
